CREATE TABLE IF NOT EXISTS students (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    course_id INTEGER NOT NULL,
    full_name TEXT NOT NULL,
    cedula TEXT NOT NULL,
    nationality TEXT NOT NULL DEFAULT 'Ecuatoriana',
    blood_type TEXT NOT NULL,
    sex TEXT NOT NULL CHECK(sex IN ('M', 'F', 'Masculino', 'Femenino')),
    birth_date DATE NOT NULL,
    age INTEGER,
    address TEXT NOT NULL,
    canton TEXT DEFAULT 'Quito',
    phone TEXT,
    email TEXT,
    education_level TEXT,
    observations TEXT,
    photo_path TEXT,
    practice_schedule TEXT,
    vehicle_id INTEGER,
    practice_instructor_id INTEGER,
    status TEXT DEFAULT 'Inscrito' CHECK(status IN ('Inscrito', 'Cursando', 'Aprobado', 'Graduado', 'Activo')),
    receipt_number INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
    FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL,
    FOREIGN KEY (practice_instructor_id) REFERENCES instructors(id) ON DELETE SET NULL
);
